version: "3.6"

services:
  sh1:
    networks:
      splunknet:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: sh1
    hostname: sh1
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      # - SPLUNK_DEPLOYMENT_SERVER=ds-sh
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_PASSWORD
      - TZ=${TZ}
    ports:
      - 8000:8000
    restart: always

  idx1:
    networks:
      splunknet:
      cmdb1:
      cmdb2:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: idx1
    hostname: idx1
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_DEPLOYMENT_SERVER=ds-sh
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_PASSWORD
      - TZ=${TZ}
    volumes:
      - idx1-var:/opt/splunk/var
      - idx1-etc:/opt/splunk/etc
    ports:
      - 8005:8000
    restart: always

  ds-sh:
    networks:
      splunknet:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: ds-sh
    hostname: ds-sh
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLE=splunk_deployment_server
      - SPLUNK_APPS_URL=https://github.com/dd-Splunk/splunk-acpv/releases/download/latest/splunk-acpv.spl
      - SPLUNKBASE_USERNAME
      - SPLUNKBASE_PASSWORD
      - SPLUNK_PASSWORD
      - TZ=${TZ}
    ports:
      - 8008:8000
    restart: always

  ds-hf:
    networks:
      cmdb1:
      cmdb2:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: ds-hf
    hostname: ds-hf
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLE=splunk_deployment_server
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/2686/release/3.13.0/download,https://splunkbase.splunk.com/app/6154/release/1.1.0/download
      - SPLUNKBASE_USERNAME
      - SPLUNKBASE_PASSWORD
      - SPLUNK_PASSWORD
      - TZ=${TZ}
    ports:
      - 8009:8000
    restart: always

  hf1:
    networks:
      splunknet:
      cmdb1:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: hf1
    hostname: hf1
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_DEPLOYMENT_SERVER=ds-hf
      - SPLUNK_ROLE=splunk_heavy_forwarder
      - SPLUNK_PASSWORD
      - JAVA_VERSION=openjdk:11
      - TZ=${TZ}
    ports:
      - 8001:8000
    restart: always

  cmdb1:
    networks:
      cmdb1:
    image: mysql:latest
    restart: always
    command: --tls_version=TLSv1.2 --local-infile=ON --secure-file-priv="${CSV_DIR}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: ${TZ}
    # ports:
    #   - '3306:3306'
    volumes:
      - cmdb1-data:/var/lib/mysql
      - ${MY_SQL_DIR}:/docker-entrypoint-initdb.d
      - .${CSV_DIR}:${CSV_DIR}

  hf2:
    networks:
      splunknet:
      cmdb2:
    image: splunk/splunk:${SPLUNK_IMAGE:-latest}
    container_name: hf2
    hostname: hf2
    platform: linux/amd64
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SEARCH_HEAD_URL=sh1
      - SPLUNK_INDEXER_URL=idx1
      - SPLUNK_HEAVY_FORWARDER_URL=hf1,hf2
      - SPLUNK_DEPLOYMENT_SERVER=ds-hf
      - SPLUNK_ROLE=splunk_heavy_forwarder
      - SPLUNK_PASSWORD
      - JAVA_VERSION=openjdk:11
      - TZ=${TZ}
    ports:
      - 8002:8000
    restart: always

  cmdb2:
    networks:
      cmdb2:
    image: mysql:latest
    restart: always
    command: --tls_version=TLSv1.2 --local-infile=ON --secure-file-priv="${CSV_DIR}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: ${TZ}
    volumes:
      - cmdb2-data:/var/lib/mysql
      - ${MY_SQL_DIR}:/docker-entrypoint-initdb.d
      - .${CSV_DIR}:${CSV_DIR}

  sidecar:
    networks:
      cmdb1:
      cmdb2:
    build: .
    volumes:
      - $PWD/hf.sh:/tmp/hf.sh

networks:
  splunknet:
  cmdb1:
  cmdb2:

volumes:
  idx1-var:
  idx1-etc:
  cmdb1-data:
  cmdb2-data:
