#!/bin/bash
source .env
MY_SQL="$MY_SQL_DIR/create-mysql.sql"
PG_SQL="$PG_SQL_DIR/create-pg.sql"

cat <<EOF | tee $MY_SQL $PG_SQL
--
-- $(date) Generated by `basename "$0"`
--
EOF

cat <<EOF >> $MY_SQL
--
USE $DB_NAME;
--
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';
--
SET GLOBAL local_infile=1;
--
-- Create DB schema from generated data
-- And load tables from generated csv data
--
EOF

for f in `ls .$CSV_DIR/*.csv`;
do
    csvsql -i mysql -d ','  --snifflimit 0 $f >> $MY_SQL
    csvsql -i postgresql -d ','  --snifflimit 0 $f >> $PG_SQL
    table=${f##*/}
    table=${table%.csv}
    echo "LOAD DATA INFILE '${f:1}' INTO TABLE \`$table\`
    FIELDS TERMINATED BY ','
    ENCLOSED BY '\"'
    LINES TERMINATED BY '\\n'
    IGNORE 1 ROWS;" >> $MY_SQL
done
