---
name: "package-app"

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tagged-release:
    name: "Package App"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create spl
        run: |
          mv app ${APP_NAME}
          COPYFILE_DISABLE=1 tar -cvzf ${APP_NAME}.spl ${APP_NAME}
        env:
          APP_NAME: ${{ github.event.repository.name }}
        # ...
      - name: Release spl
        uses: "marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            *.spl

      # - name: Upload Release
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     allowUpdates: true
      #     makeLatest: true
      #     tag: latest
      #     artifacts: ${{env.APP_NAME}}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     APP_NAME: ${{ github.event.repository.name }}.spl
