---
name: "package-app"

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tagged-release:
    name: "Package App"
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create spl
        run: |
          mv app ${APP_NAME}
          COPYFILE_DISABLE=1 tar -cvzf ${APP_NAME}.spl ${APP_NAME}
        env:
          APP_NAME: ${{ github.event.repository.name }}
        # ...
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: ${{ github.event.repository.name }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${APP_NAME}.spl
          asset_name: ${APP_NAME}.spl
          asset_content_type: application/zip

      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
